### ISSUE TITLE
Tool-tip size usability issue

### ISSUE THREAD

**Issue by freeman42x** [Tehnix/ide-haskell-hie#20]
When the entire type signature does not fit it can be confusing, see:

![](https://user-images.githubusercontent.com/1758708/38168656-0e21e83c-354b-11e8-8ad2-ad4fb407d338.png)

There is more to the signature that can be seen by moving the pointer to the right:

![](https://i.imgur.com/IZLBLX5.png)

It would probably be a good idea to set the length of the tool-tip to fit the length of the type signature and make it resizeable.

**Comment by Tehnix** [comment]
Ah, that's an annoying issue actually. This actually belongs at https://github.com/facebook-atom/atom-ide-ui/issues, since this extension merely sets up how the connection with that and HIE. atom-ide-ui takes care of all the UI stuff.

Would you mind opening an issue there and referencing this issue? Else let me know, and I'll do it (wasn't able to find anything similar while searching their issues).

**Comment by freeman42x** [comment]
@Tehnix Done. Not sure if I shouldn't have adapted the body of the issue to be specific to that package.

**Comment by Tehnix** [comment]
@razvan-panda perfect thanks! :)
