### ISSUE TITLE
Errors disappear

### ISSUE THREAD

**Issue by LukaHorvat** [Tehnix/ide-haskell-hie#25]
I've updated hie

```
hie --version
Version 0.2.0.0, Git revision 753deb91f9b9b39f14722315277d9fd587716bde (dirty) (1341 commits) x86_64 ghc-8.2.2
```

and now when I change something in a file the errors appear after a second and then disappear after another second.

It's the same issue as this https://github.com/alanz/vscode-hie-server/issues/47 so perhaps the same can be done to fix it? This is the pull request that apparently fixes it: https://github.com/alanz/haskell-lsp/pull/76

**Comment by Tehnix** [comment]
Thanks for catching this!

Since an update in Haskell-lsp fixes it, it means you'd need to wait for that to get into hie. Both the VSCode and this (Atom) clients don't touch the LSP server at all, they are just LSP clients.

That is to say, this is not something we can fix here, we'll have to wait for the fix in haskell-lsp to land in hie itself :)
